name: WKWebView Build

on:
  workflow_dispatch:
  push:
    paths:
    - wkwebview/**

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        persist-credentials: false
    - name: Build
      run: |
        cd wkwebview
        xcodebuild -scheme WebView clean archive -archivePath build/app.xcarchive CODE_SIGNING_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
